[phases.setup]
nixPkgs = ["python310", "gcc"]

[phases.install]
cmds = ["python -m venv /opt/venv", ". /opt/venv/bin/activate", "pip install -r requirements.txt"]

[phases.start]
cmd = "gunicorn greatkart.wsgi:application"
